/* Generated by Yosys 0.53+98 (git sha1 50b63c648, g++ 14.2.1 -fPIC -O3) */

(* top =  1  *)
(* src = "src/fsm.sv:2.1-56.10" *)
module fsm(CLK, nRST, data, accept);
  wire [2:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  (* src = "src/fsm.sv:3.17-3.20" *)
  input CLK;
  wire CLK;
  (* src = "src/fsm.sv:5.18-5.24" *)
  output accept;
  wire accept;
  (* src = "src/fsm.sv:4.17-4.21" *)
  input data;
  wire data;
  (* src = "src/fsm.sv:3.22-3.26" *)
  input nRST;
  wire nRST;
  (* enum_type = "$enum0" *)
  (* enum_value_000 = "\\S0" *)
  (* enum_value_001 = "\\S1" *)
  (* enum_value_010 = "\\S2" *)
  (* enum_value_011 = "\\S3" *)
  (* enum_value_100 = "\\S4" *)
  (* src = "src/fsm.sv:21.13-21.18" *)
  (* wiretype = "\\state_t" *)
  wire [2:0] state;
  INV_X1 _13_ (
    .A(state[2]),
    .ZN(_03_)
  );
  INV_X1 _14_ (
    .A(state[0]),
    .ZN(_04_)
  );
  INV_X1 _15_ (
    .A(data),
    .ZN(_05_)
  );
  INV_X1 _16_ (
    .A(state[1]),
    .ZN(_06_)
  );
  AOI22_X1 _17_ (
    .A1(state[2]),
    .A2(_01_),
    .B1(_05_),
    .B2(state[1]),
    .ZN(_07_)
  );
  AOI211_X1 _18_ (
    .A(state[0]),
    .B(_07_),
    .C1(_05_),
    .C2(state[2]),
    .ZN(_00_[2])
  );
  NAND4_X1 _19_ (
    .A1(state[2]),
    .A2(_01_),
    .A3(_04_),
    .A4(_05_),
    .ZN(_08_)
  );
  OAI211_X1 _20_ (
    .A(_03_),
    .B(state[0]),
    .C1(data),
    .C2(_06_),
    .ZN(_09_)
  );
  NAND2_X1 _21_ (
    .A1(_08_),
    .A2(_09_),
    .ZN(_00_[1])
  );
  NAND3_X1 _22_ (
    .A1(_03_),
    .A2(data),
    .A3(_06_),
    .ZN(_10_)
  );
  NAND4_X1 _23_ (
    .A1(_03_),
    .A2(state[0]),
    .A3(_05_),
    .A4(state[1]),
    .ZN(_11_)
  );
  NAND3_X1 _24_ (
    .A1(_08_),
    .A2(_10_),
    .A3(_11_),
    .ZN(_00_[0])
  );
  AND3_X1 _25_ (
    .A1(_04_),
    .A2(_06_),
    .A3(_02_),
    .ZN(accept)
  );
  DFFR_X1 _26_ (
    .CK(CLK),
    .D(_00_[0]),
    .Q(state[0]),
    .QN(_12_),
    .RN(nRST)
  );
  DFFR_X1 _27_ (
    .CK(CLK),
    .D(_00_[1]),
    .Q(state[1]),
    .QN(_01_),
    .RN(nRST)
  );
  DFFR_X1 _28_ (
    .CK(CLK),
    .D(_00_[2]),
    .Q(state[2]),
    .QN(_02_),
    .RN(nRST)
  );
endmodule
