/* Generated by Yosys 0.54 (git sha1 db72ec3bd, g++ 15.1.1 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/build/yosys/src=/usr/src/debug/yosys -fPIC -O3) */

(* top =  1  *)
(* src = "src/fsm.sv:2.1-56.10" *)
module fsm(CLK, nRST, data, accept);
  wire [2:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  (* src = "src/fsm.sv:3.17-3.20" *)
  input CLK;
  wire CLK;
  (* src = "src/fsm.sv:5.18-5.24" *)
  output accept;
  wire accept;
  (* src = "src/fsm.sv:4.17-4.21" *)
  input data;
  wire data;
  (* src = "src/fsm.sv:3.22-3.26" *)
  input nRST;
  wire nRST;
  (* enum_type = "$enum0" *)
  (* enum_value_000 = "\\S0" *)
  (* enum_value_001 = "\\S1" *)
  (* enum_value_010 = "\\S2" *)
  (* enum_value_011 = "\\S3" *)
  (* enum_value_100 = "\\S4" *)
  (* src = "src/fsm.sv:21.13-21.18" *)
  (* wiretype = "\\state_t" *)
  reg [2:0] state;
  assign _11_ = ~state[2];
  assign _01_ = ~data;
  assign _02_ = state[1] | state[0];
  assign accept = ~(state[2] | _02_);
  assign _03_ = ~(state[1] & _01_);
  assign _04_ = ~_03_;
  assign _05_ = ~(_11_ & state[0]);
  assign _06_ = state[1] | _01_;
  assign _07_ = ~(state[2] | _06_);
  assign _08_ = _11_ | _02_;
  assign _09_ = ~((_03_ | _05_) & (_08_ | data));
  assign _00_[0] = _07_ | _09_;
  assign _00_[1] = ~((_04_ | _05_) & (_08_ | data));
  assign _10_ = state[2] ? _06_ : _03_;
  assign _00_[2] = ~(state[0] | _10_);
  always @(posedge CLK, negedge nRST)
    if (!nRST) state[0] <= 1'h0;
    else state[0] <= _00_[0];
  always @(posedge CLK, negedge nRST)
    if (!nRST) state[1] <= 1'h0;
    else state[1] <= _00_[1];
  always @(posedge CLK, negedge nRST)
    if (!nRST) state[2] <= 1'h0;
    else state[2] <= _00_[2];
endmodule
